Models/Contacto.cs
namespace lapirana.Models
{
    public class Contacto
    {
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string motivo { get; set; }
        public string mensaje { get; set; }
        public string alerta { get; set; }
    }

}

Models/ErrorViewModel.cs
using System;

namespace Practica2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CompraController.cs
using Microsoft.AspNetCore.Mvc;

namespace lapirana.Controllers
{
    public class CompraController : Controller
    {
            public IActionResult Index()
            {
                return View();
            }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using lapirana.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Practica2.Models;

namespace Practica2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult QuienesSomos()
        {
            return View();
        }
        
        public IActionResult ServiciosProductos()
        {
            return View();
        }

        public IActionResult Contacto()
        {
            return View();
        }

        public IActionResult ContactoCreate(Contacto objContacto)
        {
            objContacto.alerta = "Hola " + objContacto.nombre +" "+ objContacto.apellido + " su mensaje ha sido enviado con exito";
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;

namespace lapirana.Controllers
{
    public class UsuarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult IniciarSesion()
        {
            return View();
        }
        public IActionResult Registro()
        {
            return View();
        }
        public IActionResult Actualizar()
        {
            return View();
        }
    }
}

Controllers/VentaController.cs
using Microsoft.AspNetCore.Mvc;

namespace Practica2.Controllers
{
    public class VentaController :Controller
    {
            public IActionResult Index()
            {
                return View();
            }
            public IActionResult Destacados()
            {
                return View();
            }
            public IActionResult Catalogo()
            {
                return View();
            }
            public IActionResult Servicios()
            {
                return View();
            }
    } 
}

Views/Compra/Index.cshtml
@{
    ViewData["Title"] = "Index compras";
}

<div class="text-center">
    <h1 class="display-4"> @ViewData["Title"]</h1>
</div>

Views/Compra/Pago.cshtml
@{
    ViewData["Title"] = "Pago electronico";
}

<div class="text-center">
    <h1 class="display-4"> @ViewData["Title"]</h1>
</div>

Views/Compra/Resumen.cshtml
@{
    ViewData["Title"] = "Resumen compra";
}

<div class="text-center">
    <h1 class="display-4"> @ViewData["Title"]</h1>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/contacto.cshtml
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

@{
    ViewData["Title"] = "Contacto";
}

<div class="text-center">
    <h1 class="display-4"> @ViewData["Title"]</h1>
</div>

<form asp-action="ContactoCreate">
    <div class="form-group">
        <label>Nombre</label>
        <input type="text" class="form-control" asp-for="nombre">
    </div>
    <div class="form-group">
        <label>Apellido</label>
        <input type="text" class="form-control" asp-for="apellido">
    </div>
    <div class="form-group">
        <label>Motivo</label>
        <input type="text" class="form-control" asp-for="motivo">
    </div>
    <div class="form-group">
        <label>Mensaje</label>
        <input type="textarea" class="form-control" asp-for="mensaje">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

<div>
    @Html.DisplayFor(mode1 => mode1.alerta)
</div>

Views/Home/quienessomos.cshtml
@{
    ViewData["Title"] = "Quienes somos";
}

<div class="text-center">
    <h1 class="display-4"> @ViewData["Title"]</h1>
</div>

Views/Home/serviciosproductos.cshtml
@{
    ViewData["Title"] = "Servicios y Productos";
}

<div class="text-center">
    <h1 class="display-4"> @ViewData["Title"]</h1>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - La Piraña</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="shortcut icon" href="icono.ico" type="image/x-icon">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/icono.ico" alt="La piraña" width="30px" height="30px"> La Piraña</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" data-toggle="dropdown" href="#" role="button" aria-haspopup="true">Nosotros</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="QuienesSomos">Quienes Somos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="serviciosproductos">Servicios y Productos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="contacto">Contacto</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" data-toggle="dropdown" href="#" role="button" aria-haspopup="true">Ventas Productos y Servicios</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Venta" asp-action="Destacados">Productos Destacados</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Venta" asp-action="Catalogo">Catalogo completo de productos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Venta" asp-action="Servicios">Servicios</a>
                            </div>
                        <li class="nav-item">
                            <a class="nav-link text-dark text-align-right" asp-area="" asp-controller="Usuario" asp-action="IniciarSesion">Iniciar Sesion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark text-align-right" asp-area="" asp-controller="Usuario" asp-action="Registro">Registro</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - La Piraña S.A. - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Usuario/Actualizar.cshtml
@{
    ViewData["Title"] = "Actualizar usuario";
}

<div class="text-center">
    <h1 class="display-4"> @ViewData["Title"]</h1>
</div>

Views/Usuario/Index.cshtml
@{
    ViewData["Title"] = "Index usuarios";
}

<div class="text-center">
    <h1 class="display-4"> @ViewData["Title"]</h1>
</div>

Views/Usuario/IniciarSesion.cshtml
@{
    ViewData["Title"] = "Iniciar Sesion";
}

<div class="text-center">
    <h1 class="display-4"> @ViewData["Title"]</h1>
</div>

<div class="text-center">
    <button ><a asp-controller="Usuario" asp-action="Actualizar"> Actualizar usuario</a></button>
</div>

Views/Usuario/Registro.cshtml
@{
    ViewData["Title"] = "Registrar usuario";
}

<div class="text-center">
    <h1 class="display-4"> @ViewData["Title"]</h1>
</div>

Views/Venta/Catalogo.cshtml
@{
    ViewData["Title"] = "Catalogo de productos";
}

<div class="text-center">
    <h1 class="display-4"> @ViewData["Title"]</h1>
</div>

Views/Venta/Destacados.cshtml
@{
    ViewData["Title"] = "Productos Destacados";
}

<div class="text-center">
    <h1 class="display-4"> @ViewData["Title"]</h1>
</div>

Views/Venta/Index.cshtml
@{
    ViewData["Title"] = "Index ventas";
}

<div class="text-center">
    <h1 class="display-4"> @ViewData["Title"]</h1>
</div>

Views/Venta/Servicios.cshtml
@{
    ViewData["Title"] = "Servicios";
}

<div class="text-center">
    <h1 class="display-4"> @ViewData["Title"]</h1>
</div>